version: "3.8"
services:
  postgres:
    container_name: postgres-db
    image: postgres:16
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  go-server:
    container_name: twitter-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_URI=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    networks:
      - mynetwork

networks:
  mynetwork:
