version: "3.8"
services:
  postgres:
    container_name: twitter-clone-db
    image: postgres:16
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  twitter-server:
    container_name: twitter-clone-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_URI=postgres://postgres:postgres@twitter-clone-db:5432/postgres?sslmode=disable
      - JWT_SECRET=this_is_secure_secret
    networks:
      - mynetwork

  # nginx:
  #   restart: always
  #   image: nginx:1.25.2-alpine
  #   container_name: nginx
  #   volumes:
  #     - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
  #   ports:
  #     - "80:80"
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
